name: Continuous Integrations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: fwal/setup-swift@master
      with:
          swift-version: "5"
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/VATIdValidatorPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.3
      with:
        flags: base64,unittests
        file: info.lcov
        fail_ci_if_error: true 
    
  
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
